apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-ticket-deployment
  labels:
    app: train-ticket
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-ticket
  template:
    metadata:
      labels:
        app: train-ticket
    spec:
      containers:
        - name: train-ticket
          image: bsatyam123/train-ticket:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
