apiVersion: v1
kind: Service
metadata:
  name: train-ticket-service
spec:
  type: NodePort
  selector:
    app: train-ticket
  ports:
    - port: 8080        # port inside the service
      targetPort: 8080  # maps to container port
      nodePort: 30080   # port on the node (access via localhost:30080)

